name: Auto Deploy to Windows Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create zip
        run: zip -r build.zip build/

      # 1️⃣ serverdə köhnəni ssil
      - name: Clean server folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            powershell -Command "Remove-Item -Recurse -Force ${{ secrets.TARGET }}/*"

      # 2️⃣ zip upload
      - name: Upload build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "build.zip"
          target: "C:/Users/Administrator/actions-runner/hdeploy/"
          overwrite: true

      # 3️⃣ extract + deploy
      - name: Extract on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            powershell -Command "Expand-Archive -Path C:/Users/Administrator/actions-runner/hdeploy/build.zip -DestinationPath C:/inetpub/wwwroot/app -Force"